# Generated by Django 2.2.12 on 2020-04-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('number_of_existing', models.PositiveIntegerField(default=0, verbose_name='现存数量')),
                ('category', models.CharField(choices=[('youth', '青春'), ('fiction', '小说'), ('literature', '文学'), ('art', '艺术'), ('tutorial', '教程'), ('humor', '动漫/幽默'), ('fashion', '娱乐时尚'), ('tourism', '旅游'), ('geography', '地图/地理'), ('life', '生活'), ('love', '婚恋'), ('growing', '育儿/成长'), ('health_care', '保健/心理健康'), ('physical_culture', '体育'), ('encouragement', '励志'), ('management', '管理'), ('economics', '经济'), ('law', '法律'), ('politics', '政治/军事'), ('philosophy', '哲学/宗教'), ('sociology', '社会科学'), ('ancient_books', '古籍'), ('culture', '文化'), ('history', '历史'), ('biography', '传记'), ('children', '少儿'), ('textbook', '中小学教辅'), ('foreign_language', '外语'), ('exam', '考试'), ('teaching_material', '教材'), ('reference_book', '工具书'), ('poplar_science_books', '科普读物'), ('computer', '计算机/网络'), ('medicine', '医学'), ('science', '科学技术')], db_index=True, default='youth', max_length=30, verbose_name='类别')),
                ('author', models.CharField(db_index=True, help_text='最长不超过20个字符', max_length=20, verbose_name='作者')),
                ('introduction', models.TextField(verbose_name='简介')),
                ('name', models.CharField(db_index=True, help_text='最长不超过30个字符', max_length=30, verbose_name='书名')),
                ('added_time', models.DateField(auto_now_add=True, db_index=True, verbose_name='上架时间')),
                ('ISBN', models.CharField(help_text='格式应为X-X-X-X-X(其中X为数字，2007年后为共计13位数字),包括-共计17个字符', max_length=17, primary_key=True, serialize=False, verbose_name='ISBN号')),
                ('publishing_company', models.CharField(db_index=True, default='', help_text='最长不超过20个字符', max_length=20, verbose_name='出版社')),
            ],
            options={
                'verbose_name': '图书信息',
                'verbose_name_plural': '图书信息',
            },
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_recommended_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='当前推荐数时间')),
                ('number_of_recommendation', models.PositiveIntegerField(db_index=True, default=0, verbose_name='推荐数')),
                ('book_ISBN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.BookInfo', verbose_name='图书信息')),
            ],
            options={
                'verbose_name': '图书推荐',
                'verbose_name_plural': '图书推荐',
            },
        ),
        migrations.CreateModel(
            name='BookImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books_images/%Y/%m/%d/', verbose_name='图书图片')),
                ('book_ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookInfo', verbose_name='图书信息')),
            ],
            options={
                'verbose_name': '图书图片集',
                'verbose_name_plural': '图书图片集',
            },
        ),
    ]
