# Generated by Django 3.0.6 on 2020-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEncyclopedias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(help_text='问题(不超过20个字符)', max_length=20, verbose_name='问题')),
                ('answer', models.TextField(help_text='答案', verbose_name='答案')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '居家百科问答',
                'verbose_name_plural': '居家百科问答',
                'ordering': ['-create_time'],
            },
        ),
    ]
