# Generated by Django 2.2.12 on 2020-04-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadersWish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(db_index=True, help_text='最长不超过30个字符', max_length=30, verbose_name='书名')),
                ('author', models.CharField(db_index=True, help_text='最长不超过20个字符', max_length=20, verbose_name='作者')),
                ('other_info', models.TextField(verbose_name='其他书籍相关信息')),
            ],
            options={
                'verbose_name': '读者心愿',
                'verbose_name_plural': '读者心愿',
            },
        ),
        migrations.CreateModel(
            name='SuggestedInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='最长不超过20个字符', max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('content', models.TextField(verbose_name='建议内容')),
            ],
            options={
                'verbose_name': '建议信息',
                'verbose_name_plural': '建议信息',
            },
        ),
        migrations.CreateModel(
            name='BorrowingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_borrow', models.PositiveIntegerField(db_index=True, verbose_name='借阅数量')),
                ('borrowing_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='借阅时间')),
                ('return_time', models.DateTimeField(db_index=True, verbose_name='归还时间')),
                ('book_ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookInfo', verbose_name='图书ISBN')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '借阅信息',
                'verbose_name_plural': '借阅信息',
                'unique_together': {('user_account', 'book_ISBN')},
            },
        ),
    ]
