# Generated by Django 2.2.12 on 2020-04-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nickname', models.CharField(help_text='最长不超过20个字符', max_length=20, verbose_name='昵称')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatar/%Y/%m/%d', verbose_name='头像')),
                ('password', models.CharField(db_index=True, help_text='6-12个字符', max_length=32, verbose_name='密码')),
                ('account', models.CharField(db_index=True, help_text='最长不超过13个字符', max_length=13, primary_key=True, serialize=False, verbose_name='账号')),
                ('id_number', models.CharField(help_text='18位有效身份证号', max_length=18, verbose_name='身份证号')),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('m', '男'), ('w', '女')], max_length=1, verbose_name='性别')),
                ('security_question', models.CharField(choices=[('name', '您目前的姓名是?'), ('spouse', '您配偶的姓名是?'), ('id', '您的学号(工号)是?'), ('mother', '您母亲的姓名是?'), ('father', '您父亲的姓名是?'), ('friend', '您最好的朋友姓名是?')], db_index=True, default='name', max_length=10, verbose_name='密保问题')),
                ('answer', models.CharField(db_index=True, default='', help_text='最长不超过20个字符', max_length=20, verbose_name='密保问题答案')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
