# Generated by Django 3.0.6 on 2020-05-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='产品名', max_length=10, verbose_name='产品名')),
                ('style', models.CharField(help_text='产品风格', max_length=20, verbose_name='产品风格')),
                ('site', models.CharField(help_text='产品适用场地', max_length=30, verbose_name='产品适用场地')),
                ('feature', models.TextField(blank=True, default='', help_text='产品特点', null=True, verbose_name='产品特点')),
                ('key_word', models.CharField(help_text='产品关键词', max_length=20, verbose_name='产品关键词')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='产品图片', upload_to='images/products/%Y/%m/%d', verbose_name='产品图片')),
                ('belong', models.ForeignKey(help_text='图片所属', on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='products.Products', verbose_name='图片所属')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['belong'],
            },
        ),
    ]
