# Generated by Django 3.0.6 on 2020-05-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(default='', help_text='产品名', max_length=30, verbose_name='产品名'),
        ),
        migrations.AlterField(
            model_name='products',
            name='style',
            field=models.CharField(help_text='产品风格', max_length=30, verbose_name='产品风格'),
        ),
    ]
