# Generated by Django 3.0.6 on 2020-05-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200524_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cover',
            field=models.ImageField(default='images/default/case.jpg', help_text='产品封面图片', upload_to='images/products/cover/%Y/%m/%d', verbose_name='产品封面图片'),
        ),
    ]
