# Generated by Django 3.0.6 on 2020-05-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='模型名(不超过20个字符)', max_length=20, verbose_name='模型名')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCasesVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_effect', models.FileField(help_text='模型视频', upload_to='customer_cases/videos/%Y/%m/%d', verbose_name='模型视频')),
                ('case_id', models.ForeignKey(help_text='模型id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_cases_videos', to='customer_cases.CustomerCases', verbose_name='模型id')),
            ],
            options={
                'verbose_name': '模型效果视频',
                'verbose_name_plural': '模型效果视频',
                'ordering': ['case_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerCasesImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='模型详情图', upload_to='images/detail/%Y/%m/%d', verbose_name='模型详情图')),
                ('case_id', models.ForeignKey(help_text='模型id', on_delete=django.db.models.deletion.CASCADE, related_name='customer_cases_images', to='customer_cases.CustomerCases', verbose_name='模型id')),
            ],
            options={
                'verbose_name': '模型详情图',
                'verbose_name_plural': '模型详情图',
                'ordering': ['case_id'],
            },
        ),
    ]
