# Generated by Django 3.0.6 on 2020-05-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercases',
            name='name',
            field=models.CharField(db_index=True, help_text='模型名(不超过30个字符)', max_length=30, verbose_name='模型名'),
        ),
    ]
