# Generated by Django 3.0.6 on 2020-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_time', models.DateTimeField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
                ('title', models.CharField(help_text='标题(不超过20个字符', max_length=20, verbose_name='标题')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
            ],
            options={
                'verbose_name': '咨询动态',
                'verbose_name_plural': '咨询动态',
                'ordering': ['-release_time'],
            },
        ),
    ]
